sonar.organization=govuk-one-login
sonar.projectKey=mobile-wallet-mdoc-validator

sonar.projectName=mobile-wallet-mdoc-validator
sonar.projectVersion=1.0

sonar.host.url=https://sonarcloud.io

sonar.sources=src
