name: Conventional Commits

on:
  workflow_call:

permissions:
  contents: read

jobs:
  conventional-commits:
    name: Check commit messages
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: cocogitto/cocogitto-action@52d0023b4396897f1815648e553db2ab8d782f3a # v4.2.0
        with:
          command: check
