name: Mdoc Validator - Pull Request Checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-code-quality-and-security-analysis:
    name: Run code quality and security analysis
    if: github.triggering_actor != 'dependabot[bot]'
    uses: ./.github/workflows/sonarqube.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}