name: Mdoc Validator - Release

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Must be false: each release job must finish
  cancel-in-progress: false

jobs:
  run-code-quality-and-security-analysis:
    name: Run code quality and security analysis
    uses: ./.github/workflows/sonarqube.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  validate:
    name: Validate
    uses: ./.github/workflows/validate.yaml

  conventional-commits:
    name: Conventional commits
    uses: ./.github/workflows/conventional-commits.yaml
